# Generated by Django 4.1 on 2022-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=40)),
                ('game_player_id', models.CharField(max_length=255)),
            ],
        ),
    ]
