# Generated by Django 4.1 on 2022-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_playerstats_player_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='aces',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='assists',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='deaths',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='hscount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='hspercentage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='kills',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='mvps',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='quadras',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='triples',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
