# Generated by Django 4.1 on 2022-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_remove_team_player_five_remove_team_player_four_and_more'),
        ('players', '0004_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(to='matches.team'),
        ),
    ]
