# Generated by Django 4.1 on 2022-10-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_delete_playerstats'),
        ('players', '0004_playerstats_player_id_alter_player_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='match',
        ),
        migrations.AddField(
            model_name='playerstats',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
            preserve_default=False,
        ),
    ]
