# Generated by Django 4.1 on 2022-08-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_player_team_player_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
