# Generated by Django 4.1 on 2022-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_remove_playerstats_match_playerstats_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stats',
            field=models.ManyToManyField(to='players.playerstats'),
        ),
    ]
