# Generated by Django 4.1 on 2022-08-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=255)),
                ('map', models.CharField(max_length=255)),
                ('winner', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('rounds', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=255, unique=True)),
                ('overtime_score', models.CharField(max_length=255)),
                ('second_half_score', models.CharField(max_length=255)),
                ('first_half_score', models.CharField(max_length=255)),
                ('final_score', models.CharField(max_length=255)),
                ('player_five', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player5', to='players.player')),
                ('player_four', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player4', to='players.player')),
                ('player_one', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='players.player')),
                ('player_three', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player3', to='players.player')),
                ('player_two', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team_1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='matches.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_2',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='matches.team'),
        ),
    ]
