# Generated by Django 4.1 on 2022-09-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('matches', '0003_alter_match_leavers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='leavers',
        ),
        migrations.AddField(
            model_name='match',
            name='leavers',
            field=models.ManyToManyField(null=True, to='players.player'),
        ),
    ]
