# Generated by Django 4.1 on 2022-10-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_match_leavers_match_leavers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
    ]
