# Generated by Django 4.1 on 2022-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_stats'),
        ('matches', '0005_delete_playerstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='leavers',
            field=models.ManyToManyField(to='players.player'),
        ),
    ]
