# Generated by Django 4.1 on 2022-11-14 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_player_stats'),
        ('matches', '0006_alter_match_leavers'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='epoch',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Epoch of match ending'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='leavers',
            field=models.ManyToManyField(help_text='List of leavers in a match', to='players.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='map',
            field=models.CharField(help_text='Map on which the game was played', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.CharField(help_text='FaceIT Match ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='region',
            field=models.CharField(help_text='Region of the match', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='rounds',
            field=models.CharField(help_text='Amount of rounds in a match', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(help_text='Score of the match', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(help_text='List of teams in a match', to='matches.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(help_text='Winner of the match', max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='matches',
            field=models.ForeignKey(help_text='List of matches for a team', null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(help_text='List of players in a team', to='players.player'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(help_text="Team's FaceIT ID", max_length=255),
        ),
    ]
